// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: treasury/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgChangeGasPrices struct {
	Creator   string      `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	GasPrices []*GasPrice `protobuf:"bytes,2,rep,name=gasPrices,proto3" json:"gasPrices,omitempty"`
}

func (m *MsgChangeGasPrices) Reset()         { *m = MsgChangeGasPrices{} }
func (m *MsgChangeGasPrices) String() string { return proto.CompactTextString(m) }
func (*MsgChangeGasPrices) ProtoMessage()    {}
func (*MsgChangeGasPrices) Descriptor() ([]byte, []int) {
	return fileDescriptor_805362c1c14c6627, []int{0}
}
func (m *MsgChangeGasPrices) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgChangeGasPrices) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgChangeGasPrices.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgChangeGasPrices) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgChangeGasPrices.Merge(m, src)
}
func (m *MsgChangeGasPrices) XXX_Size() int {
	return m.Size()
}
func (m *MsgChangeGasPrices) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgChangeGasPrices.DiscardUnknown(m)
}

var xxx_messageInfo_MsgChangeGasPrices proto.InternalMessageInfo

func (m *MsgChangeGasPrices) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgChangeGasPrices) GetGasPrices() []*GasPrice {
	if m != nil {
		return m.GasPrices
	}
	return nil
}

type MsgChangeGasPricesResponse struct {
}

func (m *MsgChangeGasPricesResponse) Reset()         { *m = MsgChangeGasPricesResponse{} }
func (m *MsgChangeGasPricesResponse) String() string { return proto.CompactTextString(m) }
func (*MsgChangeGasPricesResponse) ProtoMessage()    {}
func (*MsgChangeGasPricesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_805362c1c14c6627, []int{1}
}
func (m *MsgChangeGasPricesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgChangeGasPricesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgChangeGasPricesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgChangeGasPricesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgChangeGasPricesResponse.Merge(m, src)
}
func (m *MsgChangeGasPricesResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgChangeGasPricesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgChangeGasPricesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgChangeGasPricesResponse proto.InternalMessageInfo

type MsgExecuteGasBid struct {
	Creator    string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Currency   string `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	PaidAmount string `protobuf:"bytes,3,opt,name=paidAmount,proto3" json:"paidAmount,omitempty"`
	Recipient  string `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	BidNumber  uint64 `protobuf:"varint,5,opt,name=bidNumber,proto3" json:"bidNumber,omitempty"`
	FromChain  string `protobuf:"bytes,6,opt,name=fromChain,proto3" json:"fromChain,omitempty"`
}

func (m *MsgExecuteGasBid) Reset()         { *m = MsgExecuteGasBid{} }
func (m *MsgExecuteGasBid) String() string { return proto.CompactTextString(m) }
func (*MsgExecuteGasBid) ProtoMessage()    {}
func (*MsgExecuteGasBid) Descriptor() ([]byte, []int) {
	return fileDescriptor_805362c1c14c6627, []int{2}
}
func (m *MsgExecuteGasBid) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgExecuteGasBid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgExecuteGasBid.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgExecuteGasBid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExecuteGasBid.Merge(m, src)
}
func (m *MsgExecuteGasBid) XXX_Size() int {
	return m.Size()
}
func (m *MsgExecuteGasBid) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExecuteGasBid.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExecuteGasBid proto.InternalMessageInfo

func (m *MsgExecuteGasBid) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgExecuteGasBid) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *MsgExecuteGasBid) GetPaidAmount() string {
	if m != nil {
		return m.PaidAmount
	}
	return ""
}

func (m *MsgExecuteGasBid) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *MsgExecuteGasBid) GetBidNumber() uint64 {
	if m != nil {
		return m.BidNumber
	}
	return 0
}

func (m *MsgExecuteGasBid) GetFromChain() string {
	if m != nil {
		return m.FromChain
	}
	return ""
}

type MsgExecuteGasBidResponse struct {
}

func (m *MsgExecuteGasBidResponse) Reset()         { *m = MsgExecuteGasBidResponse{} }
func (m *MsgExecuteGasBidResponse) String() string { return proto.CompactTextString(m) }
func (*MsgExecuteGasBidResponse) ProtoMessage()    {}
func (*MsgExecuteGasBidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_805362c1c14c6627, []int{3}
}
func (m *MsgExecuteGasBidResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgExecuteGasBidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgExecuteGasBidResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgExecuteGasBidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExecuteGasBidResponse.Merge(m, src)
}
func (m *MsgExecuteGasBidResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgExecuteGasBidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExecuteGasBidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExecuteGasBidResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgChangeGasPrices)(nil), "dreanity.saturn.treasury.MsgChangeGasPrices")
	proto.RegisterType((*MsgChangeGasPricesResponse)(nil), "dreanity.saturn.treasury.MsgChangeGasPricesResponse")
	proto.RegisterType((*MsgExecuteGasBid)(nil), "dreanity.saturn.treasury.MsgExecuteGasBid")
	proto.RegisterType((*MsgExecuteGasBidResponse)(nil), "dreanity.saturn.treasury.MsgExecuteGasBidResponse")
}

func init() { proto.RegisterFile("treasury/tx.proto", fileDescriptor_805362c1c14c6627) }

var fileDescriptor_805362c1c14c6627 = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x4e, 0xea, 0x40,
	0x18, 0x65, 0x80, 0xcb, 0xbd, 0xcc, 0xcd, 0xcd, 0xd5, 0x59, 0x4d, 0x1a, 0xd2, 0x90, 0xae, 0x88,
	0x9a, 0x36, 0x41, 0x1f, 0x40, 0x21, 0xc4, 0x15, 0xc6, 0x74, 0xe9, 0xc6, 0x4c, 0xdb, 0xb1, 0xcc,
	0xa2, 0x33, 0xcd, 0xfc, 0x24, 0xf4, 0x2d, 0x7c, 0x26, 0x57, 0x2e, 0x59, 0xba, 0x34, 0xb0, 0xf6,
	0x1d, 0x4c, 0x4b, 0x86, 0x0a, 0x04, 0xa2, 0xcb, 0x39, 0xe7, 0x7c, 0xe7, 0xcc, 0x77, 0xf2, 0xc1,
	0x53, 0x2d, 0x29, 0x51, 0x46, 0x16, 0x81, 0x9e, 0xfb, 0xb9, 0x14, 0x5a, 0x20, 0x9c, 0x48, 0x4a,
	0x38, 0xd3, 0x85, 0xaf, 0x88, 0x36, 0x92, 0xfb, 0x56, 0xe2, 0xe0, 0x8d, 0x38, 0x25, 0xea, 0x31,
	0x97, 0x2c, 0xa6, 0xeb, 0x19, 0x2f, 0x87, 0x68, 0xaa, 0xd2, 0xf1, 0x8c, 0xf0, 0x94, 0xde, 0x12,
	0x75, 0x5f, 0x52, 0x0a, 0x61, 0xf8, 0x3b, 0x96, 0x94, 0x68, 0x21, 0x31, 0xe8, 0x83, 0x41, 0x37,
	0xb4, 0x4f, 0x74, 0x0d, 0xbb, 0xa9, 0x95, 0xe1, 0x66, 0xbf, 0x35, 0xf8, 0x3b, 0xf4, 0xfc, 0x43,
	0xb9, 0xbe, 0x75, 0x0c, 0xeb, 0x21, 0xaf, 0x07, 0x9d, 0xfd, 0xc4, 0x90, 0xaa, 0x5c, 0x70, 0x45,
	0xbd, 0x17, 0x00, 0x4f, 0xa6, 0x2a, 0x9d, 0xcc, 0x69, 0x6c, 0x74, 0xc9, 0x8f, 0x58, 0x72, 0xe4,
	0x3b, 0x0e, 0xfc, 0x13, 0x1b, 0x29, 0x29, 0x8f, 0x0b, 0xdc, 0xac, 0xa8, 0xcd, 0x1b, 0xb9, 0x10,
	0xe6, 0x84, 0x25, 0x37, 0x99, 0x30, 0x5c, 0xe3, 0x56, 0xc5, 0x7e, 0x41, 0x50, 0x0f, 0x76, 0x25,
	0x8d, 0x59, 0xce, 0x28, 0xd7, 0xb8, 0x5d, 0xd1, 0x35, 0x50, 0xb2, 0x11, 0x4b, 0xee, 0x4c, 0x16,
	0x51, 0x89, 0x7f, 0xf5, 0xc1, 0xa0, 0x1d, 0xd6, 0x40, 0xc9, 0x3e, 0x49, 0x91, 0x8d, 0x67, 0x84,
	0x71, 0xdc, 0x59, 0xcf, 0x6e, 0x00, 0xcf, 0x81, 0x78, 0x77, 0x07, 0xbb, 0xe0, 0xf0, 0x03, 0xc0,
	0xd6, 0x54, 0xa5, 0xc8, 0xc0, 0xff, 0xbb, 0xad, 0x5f, 0x1c, 0x2e, 0x72, 0xbf, 0x31, 0xe7, 0xea,
	0x27, 0x6a, 0x1b, 0x8f, 0x04, 0xfc, 0xb7, 0xdd, 0xed, 0xd9, 0x51, 0x9b, 0x2d, 0xad, 0x33, 0xfc,
	0xbe, 0xd6, 0x06, 0x8e, 0x26, 0xaf, 0x4b, 0x17, 0x2c, 0x96, 0x2e, 0x78, 0x5f, 0xba, 0xe0, 0x79,
	0xe5, 0x36, 0x16, 0x2b, 0xb7, 0xf1, 0xb6, 0x72, 0x1b, 0x0f, 0xe7, 0x29, 0xd3, 0x33, 0x13, 0xf9,
	0xb1, 0xc8, 0x02, 0xeb, 0x1b, 0xac, 0x7d, 0x83, 0x79, 0x50, 0x9f, 0x77, 0x91, 0x53, 0x15, 0x75,
	0xaa, 0x73, 0xbd, 0xfc, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x93, 0x2f, 0x4e, 0xc0, 0xf7, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	ChangeGasPrices(ctx context.Context, in *MsgChangeGasPrices, opts ...grpc.CallOption) (*MsgChangeGasPricesResponse, error)
	ExecuteGasBid(ctx context.Context, in *MsgExecuteGasBid, opts ...grpc.CallOption) (*MsgExecuteGasBidResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ChangeGasPrices(ctx context.Context, in *MsgChangeGasPrices, opts ...grpc.CallOption) (*MsgChangeGasPricesResponse, error) {
	out := new(MsgChangeGasPricesResponse)
	err := c.cc.Invoke(ctx, "/dreanity.saturn.treasury.Msg/ChangeGasPrices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ExecuteGasBid(ctx context.Context, in *MsgExecuteGasBid, opts ...grpc.CallOption) (*MsgExecuteGasBidResponse, error) {
	out := new(MsgExecuteGasBidResponse)
	err := c.cc.Invoke(ctx, "/dreanity.saturn.treasury.Msg/ExecuteGasBid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	ChangeGasPrices(context.Context, *MsgChangeGasPrices) (*MsgChangeGasPricesResponse, error)
	ExecuteGasBid(context.Context, *MsgExecuteGasBid) (*MsgExecuteGasBidResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ChangeGasPrices(ctx context.Context, req *MsgChangeGasPrices) (*MsgChangeGasPricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeGasPrices not implemented")
}
func (*UnimplementedMsgServer) ExecuteGasBid(ctx context.Context, req *MsgExecuteGasBid) (*MsgExecuteGasBidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteGasBid not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ChangeGasPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgChangeGasPrices)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ChangeGasPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dreanity.saturn.treasury.Msg/ChangeGasPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ChangeGasPrices(ctx, req.(*MsgChangeGasPrices))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ExecuteGasBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgExecuteGasBid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ExecuteGasBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dreanity.saturn.treasury.Msg/ExecuteGasBid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ExecuteGasBid(ctx, req.(*MsgExecuteGasBid))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dreanity.saturn.treasury.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChangeGasPrices",
			Handler:    _Msg_ChangeGasPrices_Handler,
		},
		{
			MethodName: "ExecuteGasBid",
			Handler:    _Msg_ExecuteGasBid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "treasury/tx.proto",
}

func (m *MsgChangeGasPrices) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgChangeGasPrices) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgChangeGasPrices) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GasPrices) > 0 {
		for iNdEx := len(m.GasPrices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GasPrices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgChangeGasPricesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgChangeGasPricesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgChangeGasPricesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgExecuteGasBid) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgExecuteGasBid) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgExecuteGasBid) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FromChain) > 0 {
		i -= len(m.FromChain)
		copy(dAtA[i:], m.FromChain)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromChain)))
		i--
		dAtA[i] = 0x32
	}
	if m.BidNumber != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BidNumber))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PaidAmount) > 0 {
		i -= len(m.PaidAmount)
		copy(dAtA[i:], m.PaidAmount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PaidAmount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Currency) > 0 {
		i -= len(m.Currency)
		copy(dAtA[i:], m.Currency)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Currency)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgExecuteGasBidResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgExecuteGasBidResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgExecuteGasBidResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgChangeGasPrices) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.GasPrices) > 0 {
		for _, e := range m.GasPrices {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgChangeGasPricesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgExecuteGasBid) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Currency)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PaidAmount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.BidNumber != 0 {
		n += 1 + sovTx(uint64(m.BidNumber))
	}
	l = len(m.FromChain)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgExecuteGasBidResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgChangeGasPrices) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgChangeGasPrices: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgChangeGasPrices: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasPrices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GasPrices = append(m.GasPrices, &GasPrice{})
			if err := m.GasPrices[len(m.GasPrices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgChangeGasPricesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgChangeGasPricesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgChangeGasPricesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgExecuteGasBid) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgExecuteGasBid: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgExecuteGasBid: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Currency", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Currency = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaidAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaidAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BidNumber", wireType)
			}
			m.BidNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BidNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromChain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromChain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgExecuteGasBidResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgExecuteGasBidResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgExecuteGasBidResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
