// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: giveaway/giveaway.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Giveaway struct {
	Index      uint64  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Duration   uint64  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	RetryCount uint64  `protobuf:"varint,3,opt,name=retryCount,proto3" json:"retryCount,omitempty"`
	Prizes     []Prize `protobuf:"bytes,4,rep,name=prizes,proto3" json:"prizes"`
}

func (m *Giveaway) Reset()         { *m = Giveaway{} }
func (m *Giveaway) String() string { return proto.CompactTextString(m) }
func (*Giveaway) ProtoMessage()    {}
func (*Giveaway) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf0a435194c6a42, []int{0}
}
func (m *Giveaway) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Giveaway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Giveaway.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Giveaway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Giveaway.Merge(m, src)
}
func (m *Giveaway) XXX_Size() int {
	return m.Size()
}
func (m *Giveaway) XXX_DiscardUnknown() {
	xxx_messageInfo_Giveaway.DiscardUnknown(m)
}

var xxx_messageInfo_Giveaway proto.InternalMessageInfo

func (m *Giveaway) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Giveaway) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Giveaway) GetRetryCount() uint64 {
	if m != nil {
		return m.RetryCount
	}
	return 0
}

func (m *Giveaway) GetPrizes() []Prize {
	if m != nil {
		return m.Prizes
	}
	return nil
}

type Prize struct {
	Amount   github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount"`
	Scale    uint32                                 `protobuf:"varint,2,opt,name=scale,proto3" json:"scale,omitempty"`
	Currency string                                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
}

func (m *Prize) Reset()         { *m = Prize{} }
func (m *Prize) String() string { return proto.CompactTextString(m) }
func (*Prize) ProtoMessage()    {}
func (*Prize) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf0a435194c6a42, []int{1}
}
func (m *Prize) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Prize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Prize.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Prize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prize.Merge(m, src)
}
func (m *Prize) XXX_Size() int {
	return m.Size()
}
func (m *Prize) XXX_DiscardUnknown() {
	xxx_messageInfo_Prize.DiscardUnknown(m)
}

var xxx_messageInfo_Prize proto.InternalMessageInfo

func (m *Prize) GetScale() uint32 {
	if m != nil {
		return m.Scale
	}
	return 0
}

func (m *Prize) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func init() {
	proto.RegisterType((*Giveaway)(nil), "dreanity.saturn.giveaway.Giveaway")
	proto.RegisterType((*Prize)(nil), "dreanity.saturn.giveaway.Prize")
}

func init() { proto.RegisterFile("giveaway/giveaway.proto", fileDescriptor_1cf0a435194c6a42) }

var fileDescriptor_1cf0a435194c6a42 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xbd, 0x4a, 0x03, 0x41,
	0x14, 0x85, 0x77, 0xcc, 0x0f, 0xc9, 0x88, 0xcd, 0x12, 0x70, 0x4d, 0x31, 0x09, 0x29, 0x24, 0x20,
	0x99, 0x05, 0x6d, 0xb5, 0x89, 0x88, 0xa4, 0x93, 0xc5, 0xca, 0x46, 0x26, 0xbb, 0xc3, 0x3a, 0x68,
	0x66, 0xc2, 0xcc, 0xac, 0x66, 0x7d, 0x09, 0xed, 0x7d, 0x0d, 0x1f, 0x22, 0x65, 0xb0, 0x12, 0x8b,
	0x20, 0xc9, 0x8b, 0xc8, 0xfc, 0x24, 0xa4, 0xb1, 0xda, 0x7b, 0xce, 0xbd, 0x77, 0xf7, 0x7c, 0x77,
	0xe1, 0x61, 0xce, 0x9e, 0x29, 0x79, 0x21, 0x65, 0xbc, 0x29, 0xf0, 0x54, 0x0a, 0x2d, 0xc2, 0x28,
	0x93, 0x94, 0x70, 0xa6, 0x4b, 0xac, 0x88, 0x2e, 0x24, 0xc7, 0x9b, 0x7e, 0xfb, 0x28, 0x15, 0x6a,
	0x22, 0xd4, 0xbd, 0x9d, 0x8b, 0x9d, 0x70, 0x4b, 0xed, 0x56, 0x2e, 0x72, 0xe1, 0x7c, 0x53, 0x39,
	0xb7, 0xf7, 0x01, 0x60, 0xe3, 0xda, 0x6f, 0x87, 0x2d, 0x58, 0x63, 0x3c, 0xa3, 0xb3, 0x08, 0x74,
	0x41, 0xbf, 0x9a, 0x38, 0x11, 0xb6, 0x61, 0x23, 0x2b, 0x24, 0xd1, 0x4c, 0xf0, 0x68, 0xcf, 0x36,
	0xb6, 0x3a, 0x44, 0x10, 0x4a, 0xaa, 0x65, 0x79, 0x29, 0x0a, 0xae, 0xa3, 0x8a, 0xed, 0xee, 0x38,
	0xe1, 0x05, 0xac, 0x4f, 0x25, 0x7b, 0xa5, 0x2a, 0xaa, 0x76, 0x2b, 0xfd, 0xfd, 0xd3, 0x0e, 0xfe,
	0x2f, 0x3a, 0xbe, 0x31, 0x73, 0xc3, 0xea, 0x7c, 0xd9, 0x09, 0x12, 0xbf, 0xd4, 0x7b, 0x03, 0xb0,
	0x66, 0xfd, 0xf0, 0x16, 0xd6, 0xc9, 0xc4, 0x7e, 0xc4, 0x64, 0x6b, 0x0e, 0xcf, 0xcd, 0xdc, 0xcf,
	0xb2, 0x73, 0x9c, 0x33, 0xfd, 0x50, 0x8c, 0x71, 0x2a, 0x26, 0x1e, 0xd7, 0x3f, 0x06, 0x2a, 0x7b,
	0x8c, 0x75, 0x39, 0xa5, 0x0a, 0x8f, 0xb8, 0xfe, 0xfa, 0x1c, 0x40, 0x7f, 0x8d, 0x11, 0xd7, 0x89,
	0x7f, 0x97, 0x01, 0x56, 0x29, 0x79, 0xa2, 0x96, 0xeb, 0x20, 0x71, 0xc2, 0x00, 0xa7, 0x85, 0x94,
	0x94, 0xa7, 0xa5, 0x45, 0x6a, 0x26, 0x5b, 0x3d, 0xbc, 0x9a, 0xaf, 0x10, 0x58, 0xac, 0x10, 0xf8,
	0x5d, 0x21, 0xf0, 0xbe, 0x46, 0xc1, 0x62, 0x8d, 0x82, 0xef, 0x35, 0x0a, 0xee, 0x4e, 0x76, 0x92,
	0x6c, 0x20, 0x63, 0x07, 0x19, 0xcf, 0xb6, 0x7f, 0xd0, 0x45, 0x1a, 0xd7, 0xed, 0xf5, 0xcf, 0xfe,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x77, 0x45, 0xc6, 0xe3, 0x01, 0x00, 0x00,
}

func (m *Giveaway) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Giveaway) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Giveaway) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Prizes) > 0 {
		for iNdEx := len(m.Prizes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Prizes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGiveaway(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.RetryCount != 0 {
		i = encodeVarintGiveaway(dAtA, i, uint64(m.RetryCount))
		i--
		dAtA[i] = 0x18
	}
	if m.Duration != 0 {
		i = encodeVarintGiveaway(dAtA, i, uint64(m.Duration))
		i--
		dAtA[i] = 0x10
	}
	if m.Index != 0 {
		i = encodeVarintGiveaway(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Prize) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Prize) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Prize) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Currency) > 0 {
		i -= len(m.Currency)
		copy(dAtA[i:], m.Currency)
		i = encodeVarintGiveaway(dAtA, i, uint64(len(m.Currency)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Scale != 0 {
		i = encodeVarintGiveaway(dAtA, i, uint64(m.Scale))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGiveaway(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGiveaway(dAtA []byte, offset int, v uint64) int {
	offset -= sovGiveaway(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Giveaway) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovGiveaway(uint64(m.Index))
	}
	if m.Duration != 0 {
		n += 1 + sovGiveaway(uint64(m.Duration))
	}
	if m.RetryCount != 0 {
		n += 1 + sovGiveaway(uint64(m.RetryCount))
	}
	if len(m.Prizes) > 0 {
		for _, e := range m.Prizes {
			l = e.Size()
			n += 1 + l + sovGiveaway(uint64(l))
		}
	}
	return n
}

func (m *Prize) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Amount.Size()
	n += 1 + l + sovGiveaway(uint64(l))
	if m.Scale != 0 {
		n += 1 + sovGiveaway(uint64(m.Scale))
	}
	l = len(m.Currency)
	if l > 0 {
		n += 1 + l + sovGiveaway(uint64(l))
	}
	return n
}

func sovGiveaway(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGiveaway(x uint64) (n int) {
	return sovGiveaway(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Giveaway) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGiveaway
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Giveaway: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Giveaway: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGiveaway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			m.Duration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGiveaway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Duration |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetryCount", wireType)
			}
			m.RetryCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGiveaway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RetryCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prizes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGiveaway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGiveaway
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGiveaway
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Prizes = append(m.Prizes, Prize{})
			if err := m.Prizes[len(m.Prizes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGiveaway(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGiveaway
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Prize) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGiveaway
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Prize: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Prize: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGiveaway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGiveaway
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGiveaway
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scale", wireType)
			}
			m.Scale = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGiveaway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Scale |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Currency", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGiveaway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGiveaway
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGiveaway
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Currency = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGiveaway(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGiveaway
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGiveaway(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGiveaway
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGiveaway
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGiveaway
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGiveaway
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGiveaway
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGiveaway
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGiveaway        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGiveaway          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGiveaway = fmt.Errorf("proto: unexpected end of group")
)
