// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: giveaway/giveaway.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Giveaway_Status int32

const (
	Giveaway_TICKETS_REGISTRATION    Giveaway_Status = 0
	Giveaway_WINNERS_DETERMINATION   Giveaway_Status = 1
	Giveaway_WINNERS_DETERMINED      Giveaway_Status = 2
	Giveaway_CANCELLED_INSUF_TICKETS Giveaway_Status = 3
)

var Giveaway_Status_name = map[int32]string{
	0: "TICKETS_REGISTRATION",
	1: "WINNERS_DETERMINATION",
	2: "WINNERS_DETERMINED",
	3: "CANCELLED_INSUF_TICKETS",
}

var Giveaway_Status_value = map[string]int32{
	"TICKETS_REGISTRATION":    0,
	"WINNERS_DETERMINATION":   1,
	"WINNERS_DETERMINED":      2,
	"CANCELLED_INSUF_TICKETS": 3,
}

func (x Giveaway_Status) String() string {
	return proto.EnumName(Giveaway_Status_name, int32(x))
}

func (Giveaway_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1cf0a435194c6a42, []int{0, 0}
}

type Giveaway struct {
	Index                uint32          `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Duration             int64           `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	CreatedAt            int64           `protobuf:"varint,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Name                 string          `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Prizes               []Prize         `protobuf:"bytes,5,rep,name=prizes,proto3" json:"prizes"`
	CompletionHeight     int64           `protobuf:"varint,6,opt,name=completionHeight,proto3" json:"completionHeight,omitempty"`
	Status               Giveaway_Status `protobuf:"varint,7,opt,name=status,proto3,enum=dreanity.saturn.giveaway.Giveaway_Status" json:"status,omitempty"`
	WinningTicketNumbers []uint32        `protobuf:"varint,8,rep,packed,name=winningTicketNumbers,proto3" json:"winningTicketNumbers,omitempty"`
}

func (m *Giveaway) Reset()         { *m = Giveaway{} }
func (m *Giveaway) String() string { return proto.CompactTextString(m) }
func (*Giveaway) ProtoMessage()    {}
func (*Giveaway) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf0a435194c6a42, []int{0}
}
func (m *Giveaway) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Giveaway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Giveaway.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Giveaway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Giveaway.Merge(m, src)
}
func (m *Giveaway) XXX_Size() int {
	return m.Size()
}
func (m *Giveaway) XXX_DiscardUnknown() {
	xxx_messageInfo_Giveaway.DiscardUnknown(m)
}

var xxx_messageInfo_Giveaway proto.InternalMessageInfo

func (m *Giveaway) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Giveaway) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Giveaway) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Giveaway) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Giveaway) GetPrizes() []Prize {
	if m != nil {
		return m.Prizes
	}
	return nil
}

func (m *Giveaway) GetCompletionHeight() int64 {
	if m != nil {
		return m.CompletionHeight
	}
	return 0
}

func (m *Giveaway) GetStatus() Giveaway_Status {
	if m != nil {
		return m.Status
	}
	return Giveaway_TICKETS_REGISTRATION
}

func (m *Giveaway) GetWinningTicketNumbers() []uint32 {
	if m != nil {
		return m.WinningTicketNumbers
	}
	return nil
}

func init() {
	proto.RegisterEnum("dreanity.saturn.giveaway.Giveaway_Status", Giveaway_Status_name, Giveaway_Status_value)
	proto.RegisterType((*Giveaway)(nil), "dreanity.saturn.giveaway.Giveaway")
}

func init() { proto.RegisterFile("giveaway/giveaway.proto", fileDescriptor_1cf0a435194c6a42) }

var fileDescriptor_1cf0a435194c6a42 = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0xe3, 0xa5, 0x0b, 0x9d, 0xd1, 0x50, 0x65, 0x05, 0x66, 0x0a, 0xca, 0xa2, 0x9d, 0x02,
	0x48, 0x89, 0x54, 0xce, 0x1c, 0xba, 0xd6, 0x8c, 0x88, 0x11, 0x90, 0x13, 0x84, 0xc4, 0xa5, 0x72,
	0x5b, 0x2b, 0xb3, 0x20, 0x4e, 0xe4, 0x38, 0x6c, 0xe5, 0x53, 0xf0, 0xa1, 0x38, 0xec, 0xb8, 0x23,
	0x27, 0x84, 0xda, 0x2f, 0x82, 0x9a, 0x3f, 0x45, 0x02, 0x76, 0x7b, 0xfd, 0xfe, 0xde, 0xf7, 0x79,
	0xf4, 0x58, 0x2f, 0x3c, 0x4a, 0xc5, 0x17, 0xce, 0x2e, 0xd9, 0x2a, 0xe8, 0x0a, 0xbf, 0x50, 0xb9,
	0xce, 0x11, 0x5e, 0x2a, 0xce, 0xa4, 0xd0, 0x2b, 0xbf, 0x64, 0xba, 0x52, 0xd2, 0xef, 0xf8, 0xd0,
	0x4e, 0xf3, 0x34, 0xaf, 0x87, 0x82, 0x6d, 0xd5, 0xcc, 0x0f, 0xed, 0x9d, 0x50, 0xa1, 0xc4, 0x57,
	0xde, 0x74, 0x4f, 0xbe, 0x9b, 0xb0, 0x7f, 0xd6, 0x02, 0x64, 0xc3, 0x7d, 0x21, 0x97, 0xfc, 0x0a,
	0x03, 0x17, 0x78, 0x87, 0xb4, 0x79, 0xa0, 0x21, 0xec, 0x2f, 0x2b, 0xc5, 0xb4, 0xc8, 0x25, 0xde,
	0x73, 0x81, 0x67, 0xd2, 0xdd, 0x1b, 0x3d, 0x86, 0x07, 0x0b, 0xc5, 0x99, 0xe6, 0xcb, 0xb1, 0xc6,
	0x66, 0x0d, 0xff, 0x34, 0x10, 0x82, 0x3d, 0xc9, 0x32, 0x8e, 0x7b, 0x2e, 0xf0, 0x0e, 0x68, 0x5d,
	0xa3, 0x17, 0xd0, 0xaa, 0xfd, 0x4b, 0xbc, 0xef, 0x9a, 0xde, 0xdd, 0xd1, 0xb1, 0x7f, 0x5b, 0x0e,
	0xff, 0xdd, 0x76, 0xee, 0xb4, 0x77, 0xfd, 0xf3, 0xd8, 0xa0, 0xed, 0x12, 0x7a, 0x0a, 0x07, 0x8b,
	0x3c, 0x2b, 0x3e, 0xf3, 0xad, 0xfd, 0x2b, 0x2e, 0xd2, 0x0b, 0x8d, 0xad, 0xda, 0xf7, 0x9f, 0x3e,
	0x1a, 0x43, 0xab, 0xd4, 0x4c, 0x57, 0x25, 0xbe, 0xe3, 0x02, 0xef, 0xde, 0xe8, 0xc9, 0xed, 0x56,
	0xdd, 0x17, 0xf8, 0x71, 0xbd, 0x40, 0xdb, 0x45, 0x34, 0x82, 0xf6, 0xa5, 0x90, 0x52, 0xc8, 0x34,
	0x11, 0x8b, 0x4f, 0x5c, 0x47, 0x55, 0x36, 0xe7, 0xaa, 0xc4, 0x7d, 0xd7, 0xf4, 0x0e, 0xe9, 0x7f,
	0xd9, 0x89, 0x82, 0x56, 0xa3, 0x82, 0x30, 0xb4, 0x93, 0x70, 0xf2, 0x9a, 0x24, 0xf1, 0x8c, 0x92,
	0xb3, 0x30, 0x4e, 0xe8, 0x38, 0x09, 0xdf, 0x46, 0x03, 0x03, 0x3d, 0x84, 0xf7, 0x3f, 0x84, 0x51,
	0x44, 0x68, 0x3c, 0x9b, 0x92, 0x84, 0xd0, 0x37, 0x61, 0xd4, 0x20, 0x80, 0x1e, 0x40, 0xf4, 0x37,
	0x22, 0xd3, 0xc1, 0x1e, 0x7a, 0x04, 0x8f, 0x26, 0xe3, 0x68, 0x42, 0xce, 0xcf, 0xc9, 0x74, 0x16,
	0x46, 0xf1, 0xfb, 0x97, 0xb3, 0x56, 0x7c, 0x60, 0x9e, 0x92, 0xeb, 0xb5, 0x03, 0x6e, 0xd6, 0x0e,
	0xf8, 0xb5, 0x76, 0xc0, 0xb7, 0x8d, 0x63, 0xdc, 0x6c, 0x1c, 0xe3, 0xc7, 0xc6, 0x31, 0x3e, 0x3e,
	0x4b, 0x85, 0xbe, 0xa8, 0xe6, 0xfe, 0x22, 0xcf, 0x82, 0x2e, 0x7e, 0xd0, 0xc4, 0x0f, 0xae, 0x76,
	0x37, 0x15, 0xe8, 0x55, 0xc1, 0xcb, 0xb9, 0x55, 0x1f, 0xc5, 0xf3, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xe7, 0x4a, 0xd4, 0x9e, 0x75, 0x02, 0x00, 0x00,
}

func (m *Giveaway) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Giveaway) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Giveaway) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WinningTicketNumbers) > 0 {
		dAtA2 := make([]byte, len(m.WinningTicketNumbers)*10)
		var j1 int
		for _, num := range m.WinningTicketNumbers {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintGiveaway(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x42
	}
	if m.Status != 0 {
		i = encodeVarintGiveaway(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x38
	}
	if m.CompletionHeight != 0 {
		i = encodeVarintGiveaway(dAtA, i, uint64(m.CompletionHeight))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Prizes) > 0 {
		for iNdEx := len(m.Prizes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Prizes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGiveaway(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintGiveaway(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x22
	}
	if m.CreatedAt != 0 {
		i = encodeVarintGiveaway(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x18
	}
	if m.Duration != 0 {
		i = encodeVarintGiveaway(dAtA, i, uint64(m.Duration))
		i--
		dAtA[i] = 0x10
	}
	if m.Index != 0 {
		i = encodeVarintGiveaway(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGiveaway(dAtA []byte, offset int, v uint64) int {
	offset -= sovGiveaway(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Giveaway) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovGiveaway(uint64(m.Index))
	}
	if m.Duration != 0 {
		n += 1 + sovGiveaway(uint64(m.Duration))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovGiveaway(uint64(m.CreatedAt))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovGiveaway(uint64(l))
	}
	if len(m.Prizes) > 0 {
		for _, e := range m.Prizes {
			l = e.Size()
			n += 1 + l + sovGiveaway(uint64(l))
		}
	}
	if m.CompletionHeight != 0 {
		n += 1 + sovGiveaway(uint64(m.CompletionHeight))
	}
	if m.Status != 0 {
		n += 1 + sovGiveaway(uint64(m.Status))
	}
	if len(m.WinningTicketNumbers) > 0 {
		l = 0
		for _, e := range m.WinningTicketNumbers {
			l += sovGiveaway(uint64(e))
		}
		n += 1 + sovGiveaway(uint64(l)) + l
	}
	return n
}

func sovGiveaway(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGiveaway(x uint64) (n int) {
	return sovGiveaway(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Giveaway) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGiveaway
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Giveaway: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Giveaway: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGiveaway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			m.Duration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGiveaway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Duration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGiveaway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGiveaway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGiveaway
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGiveaway
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prizes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGiveaway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGiveaway
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGiveaway
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Prizes = append(m.Prizes, Prize{})
			if err := m.Prizes[len(m.Prizes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletionHeight", wireType)
			}
			m.CompletionHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGiveaway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompletionHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGiveaway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= Giveaway_Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType == 0 {
				var v uint32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGiveaway
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.WinningTicketNumbers = append(m.WinningTicketNumbers, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGiveaway
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGiveaway
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthGiveaway
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.WinningTicketNumbers) == 0 {
					m.WinningTicketNumbers = make([]uint32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGiveaway
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.WinningTicketNumbers = append(m.WinningTicketNumbers, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field WinningTicketNumbers", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGiveaway(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGiveaway
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGiveaway(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGiveaway
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGiveaway
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGiveaway
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGiveaway
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGiveaway
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGiveaway
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGiveaway        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGiveaway          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGiveaway = fmt.Errorf("proto: unexpected end of group")
)
