// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: giveaway/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateGiveaway struct {
	Creator  string  `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Duration int64   `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Name     string  `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Prizes   []Prize `protobuf:"bytes,5,rep,name=prizes,proto3" json:"prizes"`
}

func (m *MsgCreateGiveaway) Reset()         { *m = MsgCreateGiveaway{} }
func (m *MsgCreateGiveaway) String() string { return proto.CompactTextString(m) }
func (*MsgCreateGiveaway) ProtoMessage()    {}
func (*MsgCreateGiveaway) Descriptor() ([]byte, []int) {
	return fileDescriptor_97ad54ab600213fb, []int{0}
}
func (m *MsgCreateGiveaway) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateGiveaway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateGiveaway.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateGiveaway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateGiveaway.Merge(m, src)
}
func (m *MsgCreateGiveaway) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateGiveaway) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateGiveaway.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateGiveaway proto.InternalMessageInfo

func (m *MsgCreateGiveaway) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateGiveaway) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *MsgCreateGiveaway) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgCreateGiveaway) GetPrizes() []Prize {
	if m != nil {
		return m.Prizes
	}
	return nil
}

type MsgCreateGiveawayResponse struct {
}

func (m *MsgCreateGiveawayResponse) Reset()         { *m = MsgCreateGiveawayResponse{} }
func (m *MsgCreateGiveawayResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateGiveawayResponse) ProtoMessage()    {}
func (*MsgCreateGiveawayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97ad54ab600213fb, []int{1}
}
func (m *MsgCreateGiveawayResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateGiveawayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateGiveawayResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateGiveawayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateGiveawayResponse.Merge(m, src)
}
func (m *MsgCreateGiveawayResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateGiveawayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateGiveawayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateGiveawayResponse proto.InternalMessageInfo

type MsgIssueTicket struct {
	Creator         string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	GiveawayId      uint32 `protobuf:"varint,2,opt,name=giveawayId,proto3" json:"giveawayId,omitempty"`
	ParticipantId   string `protobuf:"bytes,3,opt,name=participantId,proto3" json:"participantId,omitempty"`
	ParticipantName string `protobuf:"bytes,4,opt,name=participantName,proto3" json:"participantName,omitempty"`
}

func (m *MsgIssueTicket) Reset()         { *m = MsgIssueTicket{} }
func (m *MsgIssueTicket) String() string { return proto.CompactTextString(m) }
func (*MsgIssueTicket) ProtoMessage()    {}
func (*MsgIssueTicket) Descriptor() ([]byte, []int) {
	return fileDescriptor_97ad54ab600213fb, []int{2}
}
func (m *MsgIssueTicket) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgIssueTicket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgIssueTicket.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgIssueTicket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgIssueTicket.Merge(m, src)
}
func (m *MsgIssueTicket) XXX_Size() int {
	return m.Size()
}
func (m *MsgIssueTicket) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgIssueTicket.DiscardUnknown(m)
}

var xxx_messageInfo_MsgIssueTicket proto.InternalMessageInfo

func (m *MsgIssueTicket) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgIssueTicket) GetGiveawayId() uint32 {
	if m != nil {
		return m.GiveawayId
	}
	return 0
}

func (m *MsgIssueTicket) GetParticipantId() string {
	if m != nil {
		return m.ParticipantId
	}
	return ""
}

func (m *MsgIssueTicket) GetParticipantName() string {
	if m != nil {
		return m.ParticipantName
	}
	return ""
}

type MsgIssueTicketResponse struct {
}

func (m *MsgIssueTicketResponse) Reset()         { *m = MsgIssueTicketResponse{} }
func (m *MsgIssueTicketResponse) String() string { return proto.CompactTextString(m) }
func (*MsgIssueTicketResponse) ProtoMessage()    {}
func (*MsgIssueTicketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97ad54ab600213fb, []int{3}
}
func (m *MsgIssueTicketResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgIssueTicketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgIssueTicketResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgIssueTicketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgIssueTicketResponse.Merge(m, src)
}
func (m *MsgIssueTicketResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgIssueTicketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgIssueTicketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgIssueTicketResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateGiveaway)(nil), "dreanity.saturn.giveaway.MsgCreateGiveaway")
	proto.RegisterType((*MsgCreateGiveawayResponse)(nil), "dreanity.saturn.giveaway.MsgCreateGiveawayResponse")
	proto.RegisterType((*MsgIssueTicket)(nil), "dreanity.saturn.giveaway.MsgIssueTicket")
	proto.RegisterType((*MsgIssueTicketResponse)(nil), "dreanity.saturn.giveaway.MsgIssueTicketResponse")
}

func init() { proto.RegisterFile("giveaway/tx.proto", fileDescriptor_97ad54ab600213fb) }

var fileDescriptor_97ad54ab600213fb = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x8b, 0xda, 0x40,
	0x1c, 0xc5, 0x33, 0x8d, 0xb5, 0xed, 0x5f, 0xb4, 0x38, 0x48, 0x99, 0xa6, 0x10, 0x25, 0xf4, 0x10,
	0x10, 0x92, 0xa2, 0xe7, 0x5e, 0x2c, 0xa5, 0x78, 0xb0, 0x94, 0xd0, 0x53, 0x6f, 0x63, 0x32, 0xa4,
	0x43, 0x31, 0x13, 0x66, 0x26, 0xad, 0xf6, 0x53, 0xec, 0x79, 0xd9, 0x0f, 0xe4, 0xd1, 0xe3, 0x9e,
	0x96, 0x45, 0xf7, 0x83, 0x2c, 0x46, 0xa3, 0x51, 0x51, 0x76, 0x6f, 0x33, 0x8f, 0xdf, 0xff, 0xff,
	0xde, 0x3c, 0x06, 0x9a, 0x31, 0xff, 0xcb, 0xe8, 0x3f, 0x3a, 0xf3, 0xf5, 0xd4, 0x4b, 0xa5, 0xd0,
	0x02, 0x93, 0x48, 0x32, 0x9a, 0x70, 0x3d, 0xf3, 0x14, 0xd5, 0x99, 0x4c, 0xbc, 0x02, 0xb1, 0x5a,
	0xb1, 0x88, 0x45, 0x0e, 0xf9, 0xeb, 0xd3, 0x86, 0xb7, 0x5a, 0xbb, 0x15, 0xa9, 0xe4, 0xff, 0xd9,
	0x46, 0x75, 0x6e, 0x10, 0x34, 0x47, 0x2a, 0xfe, 0x22, 0x19, 0xd5, 0xec, 0xdb, 0x96, 0xc0, 0x04,
	0x5e, 0x85, 0x6b, 0x45, 0x48, 0x82, 0x3a, 0xc8, 0x7d, 0x13, 0x14, 0x57, 0x6c, 0xc1, 0xeb, 0x28,
	0x93, 0x54, 0x73, 0x91, 0x90, 0x17, 0x1d, 0xe4, 0x9a, 0xc1, 0xee, 0x8e, 0x31, 0x54, 0x12, 0x3a,
	0x61, 0xa4, 0x92, 0x8f, 0xe4, 0x67, 0xfc, 0x19, 0xaa, 0xb9, 0x9d, 0x22, 0x2f, 0x3b, 0xa6, 0x5b,
	0xeb, 0xb5, 0xbd, 0x73, 0xb1, 0xbd, 0x1f, 0x6b, 0x6e, 0x50, 0x99, 0xdf, 0xb5, 0x8d, 0x60, 0x3b,
	0xe4, 0x7c, 0x80, 0xf7, 0x27, 0xe9, 0x02, 0xa6, 0x52, 0x91, 0x28, 0xe6, 0x5c, 0x23, 0x68, 0x8c,
	0x54, 0x3c, 0x54, 0x2a, 0x63, 0x3f, 0x79, 0xf8, 0x87, 0xe9, 0x0b, 0xc1, 0x6d, 0x80, 0xc2, 0x69,
	0x18, 0xe5, 0xd1, 0xeb, 0x41, 0x49, 0xc1, 0x1f, 0xa1, 0x9e, 0x52, 0xa9, 0x79, 0xc8, 0x53, 0x9a,
	0xe8, 0x61, 0x44, 0xcc, 0x7c, 0xfe, 0x50, 0xc4, 0x2e, 0xbc, 0x2d, 0x09, 0xdf, 0xf7, 0xaf, 0x3d,
	0x96, 0x1d, 0x02, 0xef, 0x0e, 0xb3, 0x15, 0xb1, 0x7b, 0x0f, 0x08, 0xcc, 0x91, 0x8a, 0xb1, 0x84,
	0xc6, 0x51, 0xed, 0xdd, 0xf3, 0xe5, 0x9c, 0xb4, 0x60, 0xf5, 0x9f, 0x01, 0x17, 0xde, 0x98, 0x43,
	0xad, 0x5c, 0x97, 0x7b, 0x71, 0x47, 0x89, 0xb4, 0x3e, 0x3d, 0x95, 0x2c, 0xac, 0x06, 0x5f, 0xe7,
	0x4b, 0x1b, 0x2d, 0x96, 0x36, 0xba, 0x5f, 0xda, 0xe8, 0x6a, 0x65, 0x1b, 0x8b, 0x95, 0x6d, 0xdc,
	0xae, 0x6c, 0xe3, 0x57, 0x37, 0xe6, 0xfa, 0x77, 0x36, 0xf6, 0x42, 0x31, 0xf1, 0x8b, 0xad, 0xfe,
	0x66, 0xab, 0x3f, 0xf5, 0xf7, 0x3f, 0x7d, 0x96, 0x32, 0x35, 0xae, 0xe6, 0xff, 0xb4, 0xff, 0x18,
	0x00, 0x00, 0xff, 0xff, 0x35, 0x84, 0xe1, 0xad, 0x02, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateGiveaway(ctx context.Context, in *MsgCreateGiveaway, opts ...grpc.CallOption) (*MsgCreateGiveawayResponse, error)
	IssueTicket(ctx context.Context, in *MsgIssueTicket, opts ...grpc.CallOption) (*MsgIssueTicketResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateGiveaway(ctx context.Context, in *MsgCreateGiveaway, opts ...grpc.CallOption) (*MsgCreateGiveawayResponse, error) {
	out := new(MsgCreateGiveawayResponse)
	err := c.cc.Invoke(ctx, "/dreanity.saturn.giveaway.Msg/CreateGiveaway", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) IssueTicket(ctx context.Context, in *MsgIssueTicket, opts ...grpc.CallOption) (*MsgIssueTicketResponse, error) {
	out := new(MsgIssueTicketResponse)
	err := c.cc.Invoke(ctx, "/dreanity.saturn.giveaway.Msg/IssueTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateGiveaway(context.Context, *MsgCreateGiveaway) (*MsgCreateGiveawayResponse, error)
	IssueTicket(context.Context, *MsgIssueTicket) (*MsgIssueTicketResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateGiveaway(ctx context.Context, req *MsgCreateGiveaway) (*MsgCreateGiveawayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGiveaway not implemented")
}
func (*UnimplementedMsgServer) IssueTicket(ctx context.Context, req *MsgIssueTicket) (*MsgIssueTicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueTicket not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateGiveaway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateGiveaway)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateGiveaway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dreanity.saturn.giveaway.Msg/CreateGiveaway",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateGiveaway(ctx, req.(*MsgCreateGiveaway))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_IssueTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgIssueTicket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).IssueTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dreanity.saturn.giveaway.Msg/IssueTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).IssueTicket(ctx, req.(*MsgIssueTicket))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dreanity.saturn.giveaway.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGiveaway",
			Handler:    _Msg_CreateGiveaway_Handler,
		},
		{
			MethodName: "IssueTicket",
			Handler:    _Msg_IssueTicket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "giveaway/tx.proto",
}

func (m *MsgCreateGiveaway) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateGiveaway) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateGiveaway) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Prizes) > 0 {
		for iNdEx := len(m.Prizes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Prizes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x22
	}
	if m.Duration != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Duration))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateGiveawayResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateGiveawayResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateGiveawayResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgIssueTicket) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgIssueTicket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgIssueTicket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ParticipantName) > 0 {
		i -= len(m.ParticipantName)
		copy(dAtA[i:], m.ParticipantName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ParticipantName)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ParticipantId) > 0 {
		i -= len(m.ParticipantId)
		copy(dAtA[i:], m.ParticipantId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ParticipantId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.GiveawayId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.GiveawayId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgIssueTicketResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgIssueTicketResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgIssueTicketResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateGiveaway) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Duration != 0 {
		n += 1 + sovTx(uint64(m.Duration))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Prizes) > 0 {
		for _, e := range m.Prizes {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgCreateGiveawayResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgIssueTicket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.GiveawayId != 0 {
		n += 1 + sovTx(uint64(m.GiveawayId))
	}
	l = len(m.ParticipantId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ParticipantName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgIssueTicketResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateGiveaway) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateGiveaway: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateGiveaway: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			m.Duration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Duration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prizes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Prizes = append(m.Prizes, Prize{})
			if err := m.Prizes[len(m.Prizes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateGiveawayResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateGiveawayResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateGiveawayResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgIssueTicket) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgIssueTicket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgIssueTicket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GiveawayId", wireType)
			}
			m.GiveawayId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GiveawayId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticipantId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParticipantId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticipantName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParticipantName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgIssueTicketResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgIssueTicketResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgIssueTicketResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
